# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Point Cloud Library
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The Point Cloud Library (PCL) is a standalone, large scale, open project for 2D/3D image and point cloud processing.
baseurl: "/PointCloudLibrary.github.io.test" # the subpath of your site, e.g. /blog
url: "https://pointcloudlibrary.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pointclouds
github_username:  PointCloudLibrary
discord: https://discord.gg/JFFMAXS

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


api_base_url: https://pointcloudlibrary.github.io/documentation
tutorials_base_url: https://pcl-tutorials.readthedocs.io/
advanced_base_url: https://pcl-advanced.readthedocs.io/

navigation:
  - title: API Reference
    url: https://pointcloudlibrary.github.io/documentation
  - title: Tutorials
    url: https://pcl-tutorials.readthedocs.io/
  - title: Advanced
    url: https://pcl-advanced.readthedocs.io/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
